# Generated by Django 4.1.4 on 2022-12-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=10)),
                ('product1', models.CharField(max_length=30, verbose_name='Симки')),
                ('product2', models.CharField(max_length=30, verbose_name='ГСМ')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
